# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build-publish-deploy-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./AudioRezkaApp/AudioRezkaApp.sln
    - name: Build
      run: dotnet build ./AudioRezkaApp/AudioRezkaApp.sln --configuration Release --no-restore

    - name: Publish single file & self-contained
      run: |
        dotnet publish "./AudioRezkaApp\AudioRezkaApp/AudioRezkaApp.csproj" -c PublishRelease -r win-x64 -f net8.0-windows -p:PublishSingleFile=true --self-contained true -o "./out/win64_sfsc" -p:DebugType=None

    - name: Publish self-contained
      run: |
        dotnet publish "./AudioRezkaApp\AudioRezkaApp/AudioRezkaApp.csproj" -c PublishRelease -r win-x64 -f net8.0-windows -p:PublishSingleFile=false --self-contained true -o "./out/win64_sc" -p:DebugType=None

    - name: Publish single file 
      run: |
        dotnet publish "./AudioRezkaApp\AudioRezkaApp/AudioRezkaApp.csproj" -c PublishRelease -r win-x64 -f net8.0-windows -p:PublishSingleFile=true --self-contained false -o "./out/win64_sf" -p:DebugType=None


    - name: Deploy Win64
      uses: actions/upload-artifact@v4
      with:
        name: AudioRezkaApp-win64
        path: ./out/win64/
        retention-days: 90
